// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type UpstreamGroup struct {
	pulumi.CustomResourceState

	ApiVersion pulumi.StringPtrOutput     `pulumi:"apiVersion"`
	Kind       pulumi.StringPtrOutput     `pulumi:"kind"`
	Metadata   metav1.ObjectMetaPtrOutput `pulumi:"metadata"`
	Spec       UpstreamGroupSpecPtrOutput `pulumi:"spec"`
	Status     pulumi.MapOutput           `pulumi:"status"`
}

// NewUpstreamGroup registers a new resource with the given unique name, arguments, and options.
func NewUpstreamGroup(ctx *pulumi.Context,
	name string, args *UpstreamGroupArgs, opts ...pulumi.ResourceOption) (*UpstreamGroup, error) {
	if args == nil {
		args = &UpstreamGroupArgs{}
	}

	args.ApiVersion = pulumi.StringPtr("gloo.solo.io/v1")
	args.Kind = pulumi.StringPtr("UpstreamGroup")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource UpstreamGroup
	err := ctx.RegisterResource("kubernetes:gloo.solo.io/v1:UpstreamGroup", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetUpstreamGroup gets an existing UpstreamGroup resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetUpstreamGroup(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *UpstreamGroupState, opts ...pulumi.ResourceOption) (*UpstreamGroup, error) {
	var resource UpstreamGroup
	err := ctx.ReadResource("kubernetes:gloo.solo.io/v1:UpstreamGroup", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering UpstreamGroup resources.
type upstreamGroupState struct {
}

type UpstreamGroupState struct {
}

func (UpstreamGroupState) ElementType() reflect.Type {
	return reflect.TypeOf((*upstreamGroupState)(nil)).Elem()
}

type upstreamGroupArgs struct {
	ApiVersion *string                `pulumi:"apiVersion"`
	Kind       *string                `pulumi:"kind"`
	Metadata   *metav1.ObjectMeta     `pulumi:"metadata"`
	Spec       *UpstreamGroupSpec     `pulumi:"spec"`
	Status     map[string]interface{} `pulumi:"status"`
}

// The set of arguments for constructing a UpstreamGroup resource.
type UpstreamGroupArgs struct {
	ApiVersion pulumi.StringPtrInput
	Kind       pulumi.StringPtrInput
	Metadata   metav1.ObjectMetaPtrInput
	Spec       UpstreamGroupSpecPtrInput
	Status     pulumi.MapInput
}

func (UpstreamGroupArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*upstreamGroupArgs)(nil)).Elem()
}

type UpstreamGroupInput interface {
	pulumi.Input

	ToUpstreamGroupOutput() UpstreamGroupOutput
	ToUpstreamGroupOutputWithContext(ctx context.Context) UpstreamGroupOutput
}

func (*UpstreamGroup) ElementType() reflect.Type {
	return reflect.TypeOf((**UpstreamGroup)(nil)).Elem()
}

func (i *UpstreamGroup) ToUpstreamGroupOutput() UpstreamGroupOutput {
	return i.ToUpstreamGroupOutputWithContext(context.Background())
}

func (i *UpstreamGroup) ToUpstreamGroupOutputWithContext(ctx context.Context) UpstreamGroupOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UpstreamGroupOutput)
}

type UpstreamGroupOutput struct{ *pulumi.OutputState }

func (UpstreamGroupOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**UpstreamGroup)(nil)).Elem()
}

func (o UpstreamGroupOutput) ToUpstreamGroupOutput() UpstreamGroupOutput {
	return o
}

func (o UpstreamGroupOutput) ToUpstreamGroupOutputWithContext(ctx context.Context) UpstreamGroupOutput {
	return o
}

func (o UpstreamGroupOutput) ApiVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *UpstreamGroup) pulumi.StringPtrOutput { return v.ApiVersion }).(pulumi.StringPtrOutput)
}

func (o UpstreamGroupOutput) Kind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *UpstreamGroup) pulumi.StringPtrOutput { return v.Kind }).(pulumi.StringPtrOutput)
}

func (o UpstreamGroupOutput) Metadata() metav1.ObjectMetaPtrOutput {
	return o.ApplyT(func(v *UpstreamGroup) metav1.ObjectMetaPtrOutput { return v.Metadata }).(metav1.ObjectMetaPtrOutput)
}

func (o UpstreamGroupOutput) Spec() UpstreamGroupSpecPtrOutput {
	return o.ApplyT(func(v *UpstreamGroup) UpstreamGroupSpecPtrOutput { return v.Spec }).(UpstreamGroupSpecPtrOutput)
}

func (o UpstreamGroupOutput) Status() pulumi.MapOutput {
	return o.ApplyT(func(v *UpstreamGroup) pulumi.MapOutput { return v.Status }).(pulumi.MapOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*UpstreamGroupInput)(nil)).Elem(), &UpstreamGroup{})
	pulumi.RegisterOutputType(UpstreamGroupOutput{})
}
